services:
  ui-service:
    build:
      context: ./matrix-react-app
      dockerfile: ./Dockerfile
    ports:
      - "${REACTUI_PORT:-3000}:3000"
    volumes:
      - ./matrix-react-app:/app:delegated
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules: