services:
  database-service:
    image: postgres:17.3
    container_name: database-container
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DATABASE/database-config/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      matrix-network:
        aliases:
          - databaseAlias
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h databaseAlias"]
      interval: 5s
      timeout: 2s
      retries: 10

  databaseManager-service:
    image: dbeaver/cloudbeaver:24.3.5
    container_name: databaseManager-container
    ports:
      - "${CLOUD_BEAVER_PORT:-8080}:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      database-service:
        condition: service_healthy
    networks:
      - matrix-network
      
  welcome-micro-service:
    image: ratul25/project-matrix-welcome-micro-service:v2
    ports:
      - "${WS_PORT:-8080}:8080"
    depends_on:
      database-service:
        condition: service_healthy
    networks:
      - matrix-network

  login-micro-service:
    image: ratul25/project-matrix-login-micro-service:v1
    ports:
      - "${LS_PORT:-8081}:8081"
    depends_on:
      database-service:
        condition: service_healthy
    networks:
      - matrix-network
      
  bff-service:
    image: ratul25/project-matrix-bff-service:v1
    ports:
      - "${BFF_PORT:-5000}:5000"
    volumes:
      - ./BFF/matrix-node-bff:/app:delegated
      - bff_node_modules:/app/node_modules
    depends_on:
      - welcome-micro-service
    networks:
      - matrix-network
      
  ui-service:
    image: ratul25/project-matrix-ui-service:v2
    ports:
      - "${REACTUI_PORT:-3000}:3000"
    volumes:
      - ./FRONTEND/matrix-react-app:/app:delegated
      - frontend_node_modules:/app/node_modules
    depends_on:
      - bff-service
    networks:
      - matrix-network

volumes:
  postgres_data:
  cloudbeaver_data:
  bff_node_modules:
  frontend_node_modules:
  
networks:
  matrix-network:
    driver: bridge