services:
  bff-host:
    build:
      context: ./matrix-node-bff
      dockerfile: Dockerfile
    ports:
      - "${BFF_PORT:-5000}:5000"
    volumes:
      - ./matrix-node-bff:/app:delegated
      - /app/node_modules
