services:
  bff-service:
    build:
      context: ./matrix-node-bff
      dockerfile: ./Dockerfile
    ports:
      - "${BFF_PORT:-5000}:5000"
    volumes:
      - ./matrix-node-bff:/app:delegated
      - bff_node_modules:/app/node_modules

volumes:
  bff_node_modules: