services:
  database:
    image: postgres:latest
    container_name: database-container
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - matrix-network

  databaseManager:
    image: dbeaver/cloudbeaver:latest
    container_name: databaseManager-container
    ports:
      - "${CLOUD_BEAVER_PORT:-8080}:8978"
    volumes:
      - ./cloudBeaverWorkspace:/opt/cloudbeaver/workspace
    depends_on:
      - database
    networks:
      - matrix-network

volumes:
  postgres_data:
  
networks:
  matrix-network:
    driver: bridge